name: Windows2spec

on: 
  workflow_dispatch:
    inputs:
      ngrok:
        description: 'ngrok auth token'
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install curl wget qemu-kvm -y
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok
          ./ngrok config add-authtoken "${{ github.event.inputs.ngrok }}"
          nohup ./ngrok tcp --region ap 5900 &>/dev/null &
      - name: cài win và khởi chạy
        run: |
          qemu-img create -f qcow2 a.qcow2 100G
          wget -O win11.iso https://computernewb.com/isos/windows/Win10_22H2_English_x64.iso
          wget -O bios64.bin https://github.com/BlankOn/ovmf-blobs/raw/master/bios64.bin
          sudo qemu-system-x86_64 -m 6G -smp 2 -cpu host -boot order=c -drive file=win11.iso,media=cdrom -drive file=a.qcow2 -device usb-ehci,id=usb,bus=pci.0,addr=0x4 -device usb-tablet -vnc :0 -smp cores=2 -device e1000,netdev=n0 -netdev user,id=n0 -vga qxl -enable-kvm -bios bios64.bin
